Improve search by removing all whitespaces from fields and the query …
ukrainski-dom/housing-app pull request #2
Opened 2022-05-10 15:39 UTC by bartoszkp

…string

2022-05-11 11:21 UTC, jbylina requested changes
Look good 👍 Thanks for your contribution! 

In the future feel free to create a branch in `ukrainski-dom/housing-app` repository. Then I can provide review changes in code.

2022-05-11 11:21 UTC, jbylina commented on house_of_refuge/frontend/src/components/ResourceList.js
> +                .filter(r => searchQuery ? ResourceAsStringForSearch(r).search(searchQuery) > -1 : true),
Let's fix one minor bug if we touch those lines. `search` method allows the regex pattern in the argument. If the user types `+` then the app crashes.


```suggestion
                .filter(r => searchQuery ? ResourceAsStringForSearch(r).indexOf(searchQuery) > -1 : true),
```

2022-05-11 11:21 UTC, jbylina requested changes
Look good 👍 Thanks for your contribution! 

In the future feel free to create a branch in `ukrainski-dom/housing-app` repository. Then I can provide review changes in code.

2022-05-11 11:22 UTC, merged

2022-05-11 11:23 UTC, jbylina commented
> Look good 👍 Thanks for your contribution!
> 
> In the future feel free to create a branch in `ukrainski-dom/housing-app` repository. Then I can provide review changes in code.

Oh... I can commit changes in pull request 🎉 @bartoszkp merged! Thanks!

2022-05-12 08:59 UTC, bartoszkp commented
Thanks Jacek!